# -*- conf -*-
 
term=xterm-256color
include=~/.config/foot/colors.ini
initial-color-theme=light
font=monospace:size=18
font-size-adjustment=3
initial-window-size-chars=64x129

[url]
launch=xdg-open ${url}

[cursor]
style=beam
blink=yes
beam-thickness=2.5

[csd]
preferred=server

[key-bindings]
scrollback-up-half-page=none
scrollback-up-line=none
scrollback-down-half-page=none
scrollback-down-line=none
scrollback-home=none
scrollback-end=none
clipboard-copy=Control+Shift+c 
clipboard-paste=Control+Shift+v 
