[[language]]
name = "markdown"
auto-format = true
language-servers = ["marksman"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.emmet-lsp.config]
includeLanguages = {}

[[language]]
name = "html"
language-servers = [{ name = "superhtml", except-features = ["format"] }, "vscode-html-language-server", "emmet-lsp"]
auto-format = true

[[language]]
name = "bash"
scope = "source.sh"

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }
roots = [".git", "CMakeLists.txt"]

[language-server.clangd]
args = ["--enable-config"]
command = "clangd"

[language.auto-pairs]
'/' = '/' #je commente plus mon code que ce que je fais des divisions...

[[language]]
name = "ocaml"
auto-format = true
formatter = { command = "ocamlformat", args = [
  "-",
  "--impl",
  # "--enable-outside-detected-project", # Enable only if you want to format files outside of projects
] }# onEdit = true

[[language]]
name = "lua"
file-types = ["lua", "tic"]

[[language]]
name = "nix"
file-types = ["nix", "nix.tmpl"]
