
set -g status-bg                          "#ffffff"
set -gq @thm_bar_bg                       "#ffffff"

set -gq @thm_bg                           "#f9f9f9"
set -gq @thm_fg                           "#1b1b1b"
set -gq @thm_primary                      "#306b25"
set -gq @thm_inverse_primary              "#96d784"
set -gq @thm_surface_low                  "#f3f3f3"
set -gq @thm_surface                      "#eeeeee"
set -gq @thm_surface_variant              "#e8e8e8"
set -gq @thm_outline                      "#c6c6c6"
set -gq @thm_text_variant                 "#474747"

# Some variables/options must be re-set, which can be done here
set -g status-style                       "bg=#{@thm_bg},fg=#{@thm_fg}"
set -g window-active-style                "bg=#{@thm_bg},fg=#{@thm_fg}"
