unbind-key C-b
set-option -g prefix M-Space
set-option -g set-clipboard external

##############
# BEHAVIOURS #
##############


set -g base-index 1
set -g pane-base-index 1
set -g default-terminal "screen-256color"
set -sg terminal-overrides ",*:RGB"

#########
# STYLE #
#########

# set -g color_highlight "#f38ba8"

set -g pane-border-lines heavy
set -g pane-border-indicators both
set -g status-bg "#993590"
set -g status-right "#{host_short}"

set-window-option -g window-status-separator ""
set-window-option -g window-status-style bg="#993590",fg="#000000"
set-window-option -g window-status-current-style bg="#ffe493",fg="#1a3e2d"
set-window-option -g window-status-current-format "(#W)"
set-window-option -g window-status-format "[#W]"

bind -n M-e run-shell "/home/nestor/.config/tmux/scripts/prompt-popup.sh"
bind -n M-T run-shell "echo $(~/.config/tmux/scripts/tmux_popup_prompt.sh)"

#########
# BINDS #
#########
# Alt + jklh for pane movement
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
bind -n M-h select-pane -L
# Alt + n for creating a new window
bind -n M-n new-window
bind -n M-N new-session
bind -n M-H previous-window
bind -n M-L next-window
bind -n C-r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded..."

bind -n M-f if-shell "test #{window_panes} -gt 1" "kill-pane" "if-shell \"test #{session_windows} -gt 1\" \"kill-window\" \"\""
# bind -n C-i splitw -h -l 33%
bind -n M-i splitw -h -l 33%
bind -n C-Space splitw -v -l 25%
bind -n C-q popup "cht.sh --shell"
# bind -n C-z splitv
# bind -n C-z splitv

set -g mouse on
# kill empty sessions
set-hook -g client-detached 'run-shell "~/.config/tmux/kill-empty-sessions.sh"'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# run '~/.tmux/plugins/tpm/tpm'

